# Generated by Django 4.1 on 2022-09-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthmetricsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stresslevel',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], default='low', max_length=25),
        ),
    ]
