# Generated by Django 4.1 on 2022-09-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthmetricsapp', '0002_alter_user_stresslevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bloodOxygenSaturation',
            new_name='SpO2',
        ),
    ]
